create table user_details (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    email varchar(255) unique not null
);

insert into user_details (username, email) values ('evp2', 'evp2@github.com')